In [13]:
import pandas as pd

In [5]:
pd.read_csv('../raw/CRMLSSold202602.csv', encoding='latin1')

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,CloseDate,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName
0,ContraCosta,BayEast,NaN,NaN,NaN,NaN,NaN,1580000.0,1155696412,2026-02-19,...,NaN,NaN,NaN,NaN,95821,0.0,18682.0,NaN,CRMLS,CRMLS_CCBE
1,OrangeCounty,OrangeCounty,"Carpet,Tile",False,NaN,NaN,False,1100000.0,1155620121,2026-02-27,...,3.0,False,2.0,Irvine Unified,92604,NaN,5000.0,NaN,CRMLS,CRMLS_CRM
2,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,Wood,False,NaN,NaN,False,999000.0,1155350576,2026-02-27,...,NaN,False,NaN,NaN,91411,NaN,12005.0,NaN,CRMLS,CRMLS_CL
3,SanDiego,SanDiego,NaN,NaN,NaN,NaN,NaN,1650000.0,1155221012,2026-02-14,...,NaN,NaN,NaN,NaN,91910,0.0,6851.0,NaN,CRMLS,CRMLS_SAND
4,Newport,Newport,NaN,False,NaN,NaN,False,525000.0,1155192177,2026-02-24,...,4.0,False,0.0,ABC Unified,94510,0.0,18730.0,NaN,CRMLS,CRMLS_CRM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19075,CaliforniaDesert,CaliforniaDesert,"Carpet,Tile",True,NaN,NaN,True,11500.0,1020380240,2026-02-01,...,NaN,False,2.0,NaN,92270,350.0,13504.0,NaN,CRMLS,CRMLS_CDAR
19076,JoshuaTreeGateway,JoshuaTreeGateway,NaN,True,NaN,NaN,NaN,250000.0,1019908389,2026-02-13,...,NaN,False,NaN,NaN,92252,0.0,328878.0,NaN,CRMLS,CRMLS_CRM
19077,Southland,Southland,NaN,True,NaN,NaN,NaN,49999.0,541645473,2026-02-25,...,NaN,False,NaN,NaN,93534,0.0,104024.0,NaN,CRMLS,CRMLS_CRM
19078,InlandValleys,InlandValleys,NaN,True,NaN,NaN,NaN,299900.0,532189426,2026-02-27,...,NaN,False,NaN,NaN,92506,0.0,60113.0,NaN,CRMLS,CRMLS_CRM
19079,OrangeCounty,TriCounties,NaN,False,NaN,NaN,NaN,900000.0,425835813,2026-02-10,...,NaN,False,NaN,NaN,91709,0.0,82800.0,NaN,CRMLS,CRMLS_CRM

In [31]:
PATH = r"C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw/"

# Match ALL listing files
files = glob.glob(PATH + "CRMLSSold*")

print("Files found:", files)

if not files:
    raise ValueError("No SOLD files found. Check your folder or filename pattern.")

df_sold = pd.concat([pd.read_csv(f, encoding='latin1') for f in files], ignore_index=True)

print(df_sold.head())
print(df_sold.shape)

df_sold.to_csv("combined_sold.csv", index=False)
df_sold

Files found: ['C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSSold202401.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSSold202402.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSSold202403.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSSold202404.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSSold202405.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSSold202406.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSSold202407.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSSold202408.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSSold202409.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSSold202410.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSSold202411.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSSold202412.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSSold202501.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSSold202502.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSSold202503.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSSold202504.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSSold202505.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSSold202506.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSSold202507.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSSold202508.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSSold202509.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSSold202510.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSSold202511.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSSold202512.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSSold202601.csv', 'C:/Users/alexa/OneDrive/Desktop/IDX Internship/raw\\CRMLSSold202602.csv']

C:\Users\alexa\AppData\Local\Temp\ipykernel_1064\3953948424.py:11: DtypeWarning: Columns (2,36,39,56,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df_sold = pd.concat([pd.read_csv(f, encoding='latin1') for f in files], ignore_index=True)
C:\Users\alexa\AppData\Local\Temp\ipykernel_1064\3953948424.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_sold = pd.concat([pd.read_csv(f, encoding='latin1') for f in files], ignore_index=True)
C:\Users\alexa\AppData\Local\Temp\ipykernel_1064\3953948424.py:11: DtypeWarning: Columns (4,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df_sold = pd.concat([pd.read_csv(f, encoding='latin1') for f in files], ignore_index=True)

              BuyerAgentAOR              ListAgentAOR          Flooring  \
0               Mlslistings               Mlslistings  Carpet,Tile,Wood
1                HighDesert                HighDesert               NaN
2              OrangeCounty              OrangeCounty               NaN
3             InlandValleys             InlandValleys               NaN
4  SouthwestRiversideCounty  SouthwestRiversideCounty               NaN

  ViewYN WaterfrontYN BasementYN PoolPrivateYN  OriginalListPrice  ListingKey  \
0   True          NaN        NaN         False           499000.0   551985747
1    NaN          NaN        NaN           NaN                0.0   535486633
2   True          NaN        NaN           NaN            75000.0   529986282
3   True          NaN        NaN           NaN           199000.0   529618166
4   True          NaN        NaN           NaN            19500.0   522614340

               ListAgentEmail  ... PostalCode  AssociationFee  \
0       jwachter@cbnorcal.com  ...      94401          6472.0
1  eabrown@lee-associates.com  ...      92394             NaN
2             Joe@9WINWIN.com  ...      93240             NaN
3    carolthefinder@yahoo.com  ...      92308             NaN
4      jtavisola@tavisola.com  ...      93544             0.0

  LotSizeSquareFeet MiddleOrJuniorSchoolDistrict  OriginatingSystemName  \
0               NaN                          NaN                  CRMLS
1           52320.0                          NaN                  CRMLS
2          217364.0                          NaN                  CRMLS
3          217800.0                          NaN                  CRMLS
4          108883.0                          NaN                  CRMLS

   OriginatingSystemSubName BuyerAgencyCompensationType  \
0                CRMLS_MLSL                         NaN
1                 CRMLS_CRM                         NaN
2                 CRMLS_CRM                         NaN
3                 CRMLS_CRM                         NaN
4                 CRMLS_CRM                         NaN

  BuyerAgencyCompensation  latfilled  lonfilled
0                     NaN        NaN        NaN
1                     NaN        NaN        NaN
2                     NaN        NaN        NaN
3                     NaN        NaN        NaN
4                     NaN        NaN        NaN

[5 rows x 84 columns]
(568162, 84)

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,...,94401,6472.0,NaN,NaN,CRMLS,CRMLS_MLSL,NaN,NaN,NaN,NaN
1,HighDesert,HighDesert,NaN,NaN,NaN,NaN,NaN,0.0,535486633,eabrown@lee-associates.com,...,92394,NaN,52320.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
2,OrangeCounty,OrangeCounty,NaN,True,NaN,NaN,NaN,75000.0,529986282,Joe@9WINWIN.com,...,93240,NaN,217364.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
3,InlandValleys,InlandValleys,NaN,True,NaN,NaN,NaN,199000.0,529618166,carolthefinder@yahoo.com,...,92308,NaN,217800.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
4,SouthwestRiversideCounty,SouthwestRiversideCounty,NaN,True,NaN,NaN,NaN,19500.0,522614340,jtavisola@tavisola.com,...,93544,0.0,108883.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
568157,CaliforniaDesert,CaliforniaDesert,"Carpet,Tile",True,NaN,NaN,True,11500.0,1020380240,NaN,...,92270,350.0,13504.0,NaN,CRMLS,CRMLS_CDAR,NaN,NaN,NaN,NaN
568158,JoshuaTreeGateway,JoshuaTreeGateway,NaN,True,NaN,NaN,NaN,250000.0,1019908389,NaN,...,92252,0.0,328878.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
568159,Southland,Southland,NaN,True,NaN,NaN,NaN,49999.0,541645473,NaN,...,93534,0.0,104024.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
568160,InlandValleys,InlandValleys,NaN,True,NaN,NaN,NaN,299900.0,532189426,NaN,...,92506,0.0,60113.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
568161,OrangeCounty,TriCounties,NaN,False,NaN,NaN,NaN,900000.0,425835813,NaN,...,91709,0.0,82800.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN

In [33]:
pd.read_csv('combined_sold.csv').head()

C:\Users\alexa\AppData\Local\Temp\ipykernel_1064\3846618599.py:1: DtypeWarning: Columns (0,1,4,9,78,79,80,82,83) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('combined_sold.csv').head()

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,...,94401,6472.0,NaN,NaN,CRMLS,CRMLS_MLSL,NaN,NaN,NaN,NaN
1,HighDesert,HighDesert,NaN,NaN,NaN,NaN,NaN,0.0,535486633,eabrown@lee-associates.com,...,92394,NaN,52320.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
2,OrangeCounty,OrangeCounty,NaN,True,NaN,NaN,NaN,75000.0,529986282,Joe@9WINWIN.com,...,93240,NaN,217364.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
3,InlandValleys,InlandValleys,NaN,True,NaN,NaN,NaN,199000.0,529618166,carolthefinder@yahoo.com,...,92308,NaN,217800.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
4,SouthwestRiversideCounty,SouthwestRiversideCounty,NaN,True,NaN,NaN,NaN,19500.0,522614340,jtavisola@tavisola.com,...,93544,0.0,108883.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN